### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DariusCS**
Corrected CherryServers details.

### CODE REVIEW

**Comment by 1000xsh** [comment]
that list is not about marketing. what you see as text or details is a collection of experiences from other validators. if cherryservers wants to change it, they should strive to be better. the text changes will not improve the quality of cherryservers service at all.

**Comment by DariusCS** [comment]
hey @1000xsh 
Thanks for the comment. I don't think it's the right place and time to argue, but 
"Possibly oversold bandwidth" is an opinion. My corrections are all facts. 
Cherry's servers now host close to 100 validator nodes, which account for more than 8% of the total active Solana stake (source: validators.app). 
We are grateful and proud to have the opportunity to accommodate all these people, and yes, we strive to improve continuously. I am all ears for any suggestions. 
We don't trick people into the "oversold bandwidth" trap or lock our customers into long-term commitments, so everyone who uses us today has made a choice.

I'd love to offer you a 2-week free trial, no strings attached, so you can also have a first-hand opinion. 

P.S. I haven't seen anyone on the Solana Discord using dedicatednodes.io, and I can't find them on validators.app, but hey, their pull request has been accepted, and they are somehow on this list :)

**Comment by bartenbach** [comment]
I agree that "possibly oversold bandwidth" is not a fact and should probably be removed.

It's unprovable so I don't think it provides much value.

Also agree though that it is not a place for marketing. We should stick to objective facts as much as possible.

**Comment by 1000xsh** [comment]
f11231e99d25f8de8b3dbff619bfbb6224fe727e

**Pull request closed without merging**
